name: Deploy Serverus-Bot to Server

on:
  push:
    branches:
      - main
    paths:
      - 'bot/**'
      - 'cmd/**'
      - 'api/**'
      - 'serverus-bot.dockerfile'
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Transfer serverus-bot-code to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./"
        target: ${{ secrets.SERVERUS_PROJECT_PATH }}
      
    - name: Transfer docker-compose.yml to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./docker-compose.yml"
        target: ${{ secrets.SERVERUS_PROJECT_PATH }}

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          target_path="${{ secrets.SERVERUS_PROJECT_PATH }}"
          cd $target_path
          docker compose build serverus-bot-server
          docker compose down serverus-bot-server && docker compose up -d serverus-bot-server

